### ===================================================


### App Controller - /api/v1 (root)


### All endpoints are public (no authentication)


### ===================================================

@baseUrl = http://localhost:3000/api/v1


### ---------------------------------------------------


### Health check / Hello endpoint


### ---------------------------------------------------

GET {{baseUrl}}/ HTTP/1.1


### ---------------------------------------------------


### Test - Create test user


### ---------------------------------------------------

POST {{baseUrl}}/test-user HTTP/1.1


### ---------------------------------------------------


### Test - Delete test user


### ---------------------------------------------------

DELETE {{baseUrl}}/test-user HTTP/1.1
