import { NestFactory } from '@nestjs/core';
import { AppModule } from '@/app.module';
import { DatabaseService } from '@/database/database.service';
import { QcResultsService } from '@/qc-results/qc-results.service';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as argon2 from 'argon2';
import {
  sections,
  users,
  machines,
  qcTests,
  controlLots,
  qcResults,
  alerts,
  usersToAlerts,
  usersToSections,
} from '@/drizzle/schema';

// Helper to wipe the database cleanly
async function clearDatabase(db: any) {
  console.log('🗑️  Wiping existing database records to start fresh...');
  // Must delete in reverse order of dependencies to avoid foreign key errors
  await db.delete(usersToAlerts);
  await db.delete(usersToSections);
  await db.delete(alerts);
  await db.delete(qcResults);
  await db.delete(controlLots);
  await db.delete(qcTests);
  await db.delete(machines);
  await db.delete(users);
  await db.delete(sections);
  console.log('✨ Database wiped successfully!');
}

async function bootstrap() {
  // Create a headless NestJS app context (no HTTP server)
  const app = await NestFactory.createApplicationContext(AppModule);

  // Grab your existing database service from the DI container
  const databaseService = app.get(DatabaseService);
  const qcResultsService = app.get(QcResultsService);
  const db = databaseService.db;

  try {
    // 1. Wipe old data first
    await clearDatabase(db);

    console.log('📥 Loading JSON data from local file...');
    const filePath = path.join(__dirname, 'big-data.json');
    const fileContent = await fs.readFile(filePath, 'utf-8');
    const jsonData = JSON.parse(fileContent);

    console.log('🏗️  Creating default Section and Users...');

    // 2. Create a default Section to satisfy foreign keys
    const [section] = await db
      .insert(sections)
      .values({
        name: 'Main Seeded Laboratory',
        location: 'Autogenerated',
        specialization: 'OTHER',
      })
      .returning();

    // 3. Set up known credentials for local testing
    // We store the plain text password here so you know what to type,
    // but hash it for the database so your auth module works.
    const plainTextPassword = 'Password123!';
    const hashedPassword = await argon2.hash(plainTextPassword);

    // Create the Admin User
    const [adminUser] = await db
      .insert(users)
      .values({
        firstName: 'Admin',
        lastName: 'Seeder',
        email: 'admin@lab.local',
        passwordHash: hashedPassword,
        role: 'ADMIN',
      })
      .returning();

    // Create Multiple Technician Users
    const techniciansToInsert = [
      {
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@lab.local',
        passwordHash: hashedPassword,
        role: 'TECHNICIAN' as const,
      },
      {
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@lab.local',
        passwordHash: hashedPassword,
        role: 'TECHNICIAN' as const,
      },
      {
        firstName: 'Ahmed',
        lastName: 'Tarek',
        email: 'ahmed.t@lab.local',
        passwordHash: hashedPassword,
        role: 'TECHNICIAN' as const,
      },
    ];

    const insertedTechs = await db
      .insert(users)
      .values(techniciansToInsert)
      .returning();

    await db.insert(usersToSections).values([
      { userId: adminUser.id, sectionId: section.id },
      ...insertedTechs.map((tech) => ({
        userId: tech.id,
        sectionId: section.id,
      })),
    ]);

    // Combine all users so we can randomly assign who performed a QC Test
    const allUsers = [adminUser, ...insertedTechs];

    console.log('🔄 Processing JSON data...');

    // 4. Iterate through Equipment (Machines)
    for (const eqpCode of Object.keys(jsonData)) {
      console.log(`Setting up Machine ID/Code: ${eqpCode}...`);

      const [machine] = await db
        .insert(machines)
        .values({
          name: `Machine ${eqpCode}`,
          hospCode: '2', // Based on the sample data
          sectionId: section.id,
          currentStatus: 'IDLE',
        })
        .returning();

      const tests = jsonData[eqpCode];

      // 5. Iterate through Tests for this Machine
      for (const testCode of Object.keys(tests)) {
        const [qcTest] = await db
          .insert(qcTests)
          .values({
            testName: testCode,
            testType: 'Autogenerated',
            machineId: machine.id,
          })
          .returning();

        // 6. Derive lot statistics from numeric records
        const records = tests[testCode];
        const numericValues = records
          .map((record: any) => parseFloat(record.TESTRESULT))
          .filter((v: number) => !isNaN(v));

        if (numericValues.length === 0) {
          console.warn(
            `⚠️  Skipping test ${testCode} because no numeric results were found.`,
          );
          continue;
        }

        const mean =
          numericValues.reduce((sum: number, val: number) => sum + val, 0) /
          numericValues.length;
        const variance =
          numericValues.reduce(
            (sum: number, val: number) => sum + Math.pow(val - mean, 2),
            0,
          ) / numericValues.length;
        const std = Math.sqrt(variance);
        const safeStd = std > 0 ? std : 1;

        // 7. Create a control lot with calculated limits
        const expirationDate = new Date();
        expirationDate.setFullYear(expirationDate.getFullYear() + 1);

        const [controlLot] = await db
          .insert(controlLots)
          .values({
            testId: qcTest.id,
            lotNumber: `LOT-${eqpCode}-${testCode}`,
            expirationDate: expirationDate,
            targetValue: mean,
            mean,
            standardDeviation: safeStd,
            upperControlLimit: mean + 3 * safeStd,
            lowerControlLimit: mean - 3 * safeStd,
            upperWarningLimit: mean + 2 * safeStd,
            lowerWarningLimit: mean - 2 * safeStd,
            isActive: true,
          })
          .returning();

        let insertedCount = 0;
        // 8. Create QC results through service to trigger alert logic
        for (const record of records) {
          // Parse float to protect against strings like "pg/ml"
          const measuredValue = parseFloat(record.TESTRESULT);

          if (isNaN(measuredValue)) {
            console.warn(
              `⚠️  Skipping invalid numeric result for Test ${testCode}: "${record.TESTRESULT}"`,
            );
            continue;
          }

          // Pick a random user to assign performer
          const randomUser =
            allUsers[Math.floor(Math.random() * allUsers.length)];

          await qcResultsService.create(
            {
              machineId: machine.id,
              results: [
                {
                  measuredValue,
                  lotId: controlLot.id,
                  comments: undefined,
                }
              ]
            },
            randomUser.id,
          );
          insertedCount += 1;
        }

        console.log(
          `✅ Inserted ${insertedCount} results for Test ${testCode}`,
        );
      }
    }

    console.log('\n🎉 Database seeding completed successfully!');
    console.log('--------------------------------------------------');
    console.log('🔑 USER CREDENTIALS FOR LOGIN:');
    console.log(`All users share the same password:  ${plainTextPassword}`);
    console.log('\nEmails available to log in with:');
    allUsers.forEach((u) => console.log(` - ${u.email} (${u.role})`));
    console.log('--------------------------------------------------\n');
  } catch (error) {
    console.error('❌ Seeding failed:', error);
  } finally {
    // Ensure the NestJS application context closes properly so the script exits
    await app.close();
  }
}

bootstrap();
