name: PR Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    name: Backend (NestJS) Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install backend dependencies
        run: npm ci

      - name: Run backend tests
        run: npm run test

  test-frontend:
    name: Frontend (Next.js) Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install frontend dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm run test
